version: 2

jobs:
  Apollo Client:
    docker:
      - image: circleci/node:8

    steps:
      - checkout
      - run: cd client && npm ci
      - run: cd client && npm test
      - run: cd client && npx apollo client:check

      - run: |
          if [ "${CIRCLE_BRANCH}" == "master" ]; then
            cd client && npx apollo client:push
          fi
  Apollo Server:
    docker:
      - image: circleci/node:8

 # Service container image made available to the primary container at `host: localhost`
      - image: dwmkerr/dynamodb:41
        # custom entrypoint to limit RAM to 1G to prevent OOM on CircleCI 2.0.
        # https://circleci.com/docs/2.0/configuration-reference/#docker--machine--macosexecutor
        entrypoint: ["java", "-Xmx1G", "-jar", "DynamoDBLocal.jar"]
    steps:
      - checkout
      - run: cd server && npm ci
      - run: cd server && npm test

      - run:
          name: Starting server
          command: cd server && npm run start:ci
          background: true

      - run: sleep 5
      - run: cd server && npx apollo service:check

      - run: |
          if [ "${CIRCLE_BRANCH}" == "master" ]; then
            cd server && npx apollo service:push
          fi
workflows:
  version: 2
  Build and Test:
    jobs:
      - Apollo Client
      - Apollo Server
